tapis.db.jdbc.url=jdbc:postgresql://localhost:5433/tapissecdb
tapis.db.password=password
tapis.db.user=tapis
tapis.site.id=tacc
tapis.sk.vault.disable=true
tapis.sk.vault.address=http://localhost:8200
tapis.tenant.svc.baseurl=https://admin.develop.tapis.io
tapis.test.base.url=http://localhost:8090/v3/security
